name: Deploy Frontend


on:
  push:
    branches:
      - main


jobs:

  build-and-push:

    runs-on: ubuntu-latest


    steps:


      - name: Checkout code
        uses: actions/checkout@v5



      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5

        with:

          aws-access-key-id:
            ${{ secrets.AWS_ACCESS_KEY_ID }}

          aws-secret-access-key:
            ${{ secrets.AWS_SECRET_ACCESS_KEY }}

          aws-region:
            ${{ secrets.AWS_REGION }}



      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2



      - name: Build Web image

        run: |

          docker build \
          -f apps/web/Dockerfile \
          -t enterprise-web .



      - name: Push Web image

        run: |

          docker tag enterprise-web:latest \
          ${{ secrets.ECR_REGISTRY }}/enterprise/enterprise-web:latest


          docker push \
          ${{ secrets.ECR_REGISTRY }}/enterprise/enterprise-web:latest